### ISSUE TITLE
Is this possible to mount S3 under non-root user?

### ISSUE THREAD

**Issue by empeekdev** [awslabs/mountpoint-s3-csi-driver#118]
/feature

**Is your feature request related to a problem? Please describe.**
Hi! I’m trying to mount S3 bucket to pod under non-root user
Bucket itself seems to be mounted with no problems, but for some reason when I go to mount path I got permission denied error. 

File permissions look weird
`ls -la /tmp/` result:

```
total 0
drwxrwxrwt 1 root root 16 Jan  8 11:22 .
drwxr-xr-x 1 root root 28 Jan  8 11:22 ..
d????????? ? ?    ?     ?            ? s3
```

Deployment.yaml file:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: internal
spec:
  selector:
    matchLabels:
      app: 
  replicas: 1
  template:
    metadata:
      labels:
        app: 
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: foobarservice
        image: foobarimage
        command:
          - bash
        args:
          - '-c'
          - while true; do echo 'This is an infinite loop'; done
        volumeMounts:
        - name: s3-mount-point
          mountPath: /tmp/s3
      volumes:
        - name: s3-mount-point
          persistentVolumeClaim:
            claimName: s3-mount-point-pvc
```
**Describe the solution you'd like in detail**
Ability to run under non-root user

**Describe alternatives you've considered**
I tried to manage permissions using init-container and chown-ing folder but no success, even more init container has permissions denied error as well. S3 mounting working only if container is running root user.

**Additional context**
