### ISSUE TITLE
Feature - Dynamic Provisioning

### ISSUE THREAD

**Issue by rainerleber** [awslabs/mountpoint-s3-csi-driver#125]
/feature

I have a multi cloud application which we want to provide on different Hyperscalers. For this purpose I have the use case to write data to a Azure SA, S3 on AWS,  and so on 
For Azure Environments I use the Azure Blob CSI Driver which have the ability to dynamically provision Azure Storage Accounts.
Same for GCP.

At the moment it's not possible to dynamically create s3 buckets.

This Issue urgently requests the ability to provision s3 buckets like in other csi drivers.  

**Describe alternatives you've considered**
Manual process, Crossplane or Terraform is an alternative but there should be a solution to provision S3 Buckets from the CSI dynamically to have the best variability.

**Additional context**

**Comment by dlakhaws** [comment]
Thank you for the feature request. Dynamic provisioning is something we are tracking and will post updates as we have them.

**Comment by LMantovan** [comment]
+1

**Comment by LMantovan** [comment]
Have you got a planned release date for this feature? I am interested too

**Comment by geowalrus4gh** [comment]
+1

**Comment by dannycjones** [comment]
There's no update we can share right now.

If you would like to show interest on this feature, please use the thumbs up reaction (👍) on the main issue as this is our primary way to track interest on GitHub.

**Comment by Japson0** [comment]
I have a similar need, I want to create a PV for each namespace on K8S to specify a Bucket, and each pod in this namespace can be specified by creating a different PVC and then specifying a different directory under the same Bucket.
Just like this:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Mi  # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - endpoint-url http://168.5.80.43:9000
    - read-only
    - prefix dev3/

  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume # must be unique
    volumeAttributes:
      bucketName: emlp
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-2
spec:
  capacity:
    storage: 6Mi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - endpoint-url http://168.5.80.43:9000
    - allow-delete

  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume-2 # must be unique
    volumeAttributes:
      bucketName: s3-csi-driver-2
      prefix: data/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv-2
spec:
  capacity:
    storage: 6Mi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - endpoint-url http://168.5.80.43:9000
    - allow-delete

  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume-2 # must be unique
    volumeAttributes:
      bucketName: s3-csi-driver-2
      prefix: data-2/  
```
