### ISSUE TITLE
Dual stack S3 endpoint support/documentation

### ISSUE THREAD

**Issue by happosade** [awslabs/mountpoint-s3-csi-driver#158]
/feature

**Is your feature request related to a problem? Please describe.**
If VPCs are created with DNS64 and NAT64 located in other VPC (e.g. Egress VPC), this adds lots of latency and costs compared to using dual stack endpoints that can be reached with IPv6.

**Describe the solution you'd like in detail**
My assumption is that it only needs option to configure if dual stack endpoints should be used or not. (Seems like they're off by default https://github.com/awslabs/mountpoint-s3/blob/main/mountpoint-s3-client/src/endpoint_config.rs#L67)

If this already supported, I think the documentation should be improved a bit, so it would be clear that it is already working as expected.

**Comment by jjkr** [comment]
This is supported using the `dual-stack` mount option. Mountpoint has some documentation for that option [here](https://github.com/awslabs/mountpoint-s3/blob/afd42dd6f8eb33a2d6546173fd87c616f4cfe11b/doc/CONFIGURATION.md#endpoints-and-aws-privatelink). I agree the documentation on the CSI side can be more clear and will leave this issue open to make the documentation improvements. In the meantime, this is what an example persistent volume configuration looks like using dual stack endpoints.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - region us-west-2
    - dual-stack
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: s3-csi-driver
```
