### ISSUE TITLE
PVC error "storageClassName does not match". Takes the default gp3

### ISSUE THREAD

**Issue by Smana** [awslabs/mountpoint-s3-csi-driver#182]
/kind bug

**What happened?**

Using the static provisioning guide, when the pvc is created it takes automatically the default storageClass `gp3`

```console
kubectl get sc gp3
NAME            PROVISIONER       RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp3 (default)   ebs.csi.aws.com   Delete          WaitForFirstConsumer   true                   153d
```

And I get this error when I describe the pvc
```console
kubectl describe pvc -n platform text-generation-inference-s3 | grep -A 5 ^Events
Events:
  Type     Reason          Age                   From                         Message
  ----     ------          ----                  ----                         -------
  Warning  VolumeMismatch  2m31s (x62 over 17m)  persistentvolume-controller  Cannot bind to requested volume "text-generation-inference-s3": storageClassName does not match
```

**What you expected to happen?**

Expecting the PVCs to be ready and they're not
```console
kubectl get pvc -n platform |grep text
text-embeddings-inference-s3      Pending   text-embeddings-inference-s3               0                         gp3            20m
text-generation-inference-s3      Pending   text-generation-inference-s3               0                         gp3            20m
```

The PVs are ready
```console
kubectl get pv -n platform|grep text
text-embeddings-inference-s3               10Gi       ROX            Retain           Available                                                                                                                                                      21m
text-generation-inference-s3               10Gi       ROX            Retain           Available                
```

**How to reproduce it (as minimally and precisely as possible)?**

Here are the manifests
```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    meta.helm.sh/release-name: text-inference
    meta.helm.sh/release-namespace: platform
  labels:
    app.kubernetes.io/instance: text-inference
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: text-generation-inference
    helm.sh/chart: helm-universal-0.0.0
  name: text-generation-inference-s3
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 10Gi
  csi:
    driver: s3.csi.aws.com
    volumeAttributes:
      bucketName: <REDACTED>
    volumeHandle: s3-csi-driver-volume
  mountOptions:
  - allow-delete
  - region eu-west-3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: text-inference
    meta.helm.sh/release-namespace: platform
  labels:
    app.kubernetes.io/instance: text-inference
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: text-generation-inference
    helm.sh/chart: helm-universal-0.0.0
  name: text-generation-inference-s3
  namespace: platform
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: ""
  volumeName: text-generation-inference-s3
```

**Environment**
- Kubernetes version (use `kubectl version`):
```console
kubectl version
Client Version: v1.28.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7-eks-b9c9ed7
```
- Driver version: v1.5.1
