### ISSUE TITLE
Support PVs with object keys instead of buckets

### ISSUE THREAD

**Issue by nash-3as** [awslabs/mountpoint-s3-csi-driver#198]
/feature

**Is your feature request related to a problem? Please describe.**
I would like to use one bucket to provision multiple volumes (PVs), each of which is mapped into a folder in the S3 bucket. Creating a different S3 bucket for each volume is just not feasible

**Describe the solution you'd like in detail**
In the PV specs:
```
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - allow-delete
    - region eu-central-1
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: my-volume
    volumeAttributes:
      bucketName: my-bucket
     directory: path/to/directory # optional
```

**Describe alternatives you've considered**
Using EFS, but handling files in the EFS volumes are not as easy.

**Additional context**

**Comment by passaro** [comment]
Hi @nash-3as. Mountpoint supports specifying a prefix for the bucket you want to mount (under `mountOptions`). That would look like this:
```
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadWriteMany # supported options: ReadWriteMany / ReadOnlyMany
  mountOptions:
    - allow-delete
    - region eu-central-1
    - prefix: prefix/in/my-bucket/ # must end in "/"
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: my-volume
    volumeAttributes:
      bucketName: my-bucket
```

Then you could configure multiple volumes with the same bucket but different prefixes.

Does that cover your use case?
