### ISSUE TITLE
hostPath type check failed: /run/systemd/private is not a socket file

### ISSUE THREAD

**Issue by bpereto** [awslabs/mountpoint-s3-csi-driver#213]
/kind bug

**What happened?**
csi driver did not start and stuck on Init

 ```
   Warning  FailedMount      2m19s (x104 over 3h17m)  kubelet       MountVolume.SetUp failed for volume "systemd-bus" : hostPath type check failed: /run/systemd/private is not a socket file
   ```

**What you expected to happen?**
CSI DaemonSet does initialize and start

**How to reproduce it (as minimally and precisely as possible)?**
Talos OS 1.7.4

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-mountpoint-s3-csi-driver
  namespace: kube-system
spec:
  interval: 4h
  url: https://awslabs.github.io/mountpoint-s3-csi-driver
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: s3-csi-driver
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-mountpoint-s3-csi-driver
      sourceRef:
        kind: HelmRepository
        name: aws-mountpoint-s3-csi-driver
        namespace: kube-system
      interval: 1m
  values:
  ```

**Anything else we need to know?**:

**Environment**
- Talos OS 1.7.4
- Kubernetes version (use `kubectl version`): 1.30.0
- Driver version:
