### ISSUE TITLE
AWS_IO_TLS_CTX_ERROR while mounting

### ISSUE THREAD

**Issue by maxemontio** [awslabs/mountpoint-s3-csi-driver#241]
Hi!

When i try to mount a PVC to a pod, i am getting the error:
```
MountVolume.SetUp failed for volume "s3-pv" : rpc error: code = Internal desc = Could not mount "<redacted>" at "/var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount": Mount failed: Failed to start service output: Error: Failed to create S3 client Caused by: 0: invalid AWS credentials 1: CRT error 1033: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context Error: Failed to create mount process
```
logs from the pod:
```
I0822 12:39:15.074277       1 node.go:65] NodePublishVolume: req: volume_id:"s3-csi-driver-volume" target_path:"/var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount" volume_capability:<mount:<mount_flags:"allow-other" mount_flags:"allow-delete" mount_flags:"region us-east-1" mount_flags:"prefix tmp/" > access_mode:<mode:MULTI_NODE_MULTI_WRITER > > volume_context:<key:"bucketName" value:"<redacted>" > 
I0822 12:39:15.074323       1 node.go:112] NodePublishVolume: mounting <redacted> at /var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount with options [--allow-delete --allow-other --prefix=tmp/ --region=us-east-1]
E0822 12:39:15.115224       1 driver.go:113] GRPC error: rpc error: code = Internal desc = Could not mount "<redacted>" at "/var/lib/kubelet/pods/116ccb23-c268-4c4b-9396-4e78143251a5/volumes/kubernetes.io~csi/s3-pv/mount": Mount failed: Failed to start service output: Error: Failed to create S3 client  Caused by:     0: invalid AWS credentials     1: CRT error 1033: aws-c-io: AWS_IO_TLS_CTX_ERROR, Failed to create tls context Error: Failed to create mount process
```

We use IRSA.

values.yaml:
```
node:
  serviceAccount:
    create: true
    name: s3-csi-driver-sa
    annotations:
      "eks.amazonaws.com/role-arn": <redacted>
  resources:
    requests:
      cpu: null
      memory: 32Mi
    limits:
      cpu: null
      memory: 256Mi
  tolerateAllTaints: false

sidecars:
  nodeDriverRegistrar:
    resources:
      requests:
        cpu: null
        memory: 32Mi
      limits:
        cpu: null
        memory: 128Mi
  livenessProbe:
    resources:
      requests:
        cpu: null
        memory: 32Mi
      limits:
        cpu: null
        memory: 128Mi
```
iam policy:
```
{
    "Statement": [
        {
            "Action": "s3:ListBucket",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::*",
            "Sid": "MountpointFullBucketAccess"
        },
        {
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:AbortMultipartUpload"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::*/*",
            "Sid": "MountpointFullObjectAccess"
        }
    ],
    "Version": "2012-10-17"
}
```
trust policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<redacted>:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/<redacted_id>"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/<redacted_id>:aud": "sts.amazonaws.com",
                    "oidc.eks.us-east-1.amazonaws.com/id/<redacted_id>:sub": "system:serviceaccount:aws-mountpoint-s3-csi-driver:s3-csi-driver-sa"
                }
            }
        }
    ]
}
```
This is what i use for testing:
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - allow-other
    - allow-delete
    - region us-east-1
    - prefix tmp/
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: <redacted>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: s3-pv

---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: s3-pvc
  containers:
    - name: ubuntu
      image: ubuntu
      command:
        - "sleep"
        - "604800"
      volumeMounts:
        - name: data
          mountPath: /mnt/data
```
What could it be? We have another apps which are using irsa without any problem in the same cluster. It looks more like a tls error than a configuration error.

**Environment**
- Driver version: 1.8.0
- Kubernetes EKS version: 1.29
- Kubelet version: v1.29.3-eks-ae9a62a
- Containerd version: containerd://1.7.11
- OS: Amazon Linux 2
- Ami version: [v20240703](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20240703)
