### ISSUE TITLE
Feature Request: Specify Bucket Name Inside StorageClass for S3 CSI Driver

### ISSUE THREAD

**Issue by matanbaruch** [awslabs/mountpoint-s3-csi-driver#250]
**Is your feature request related to a problem? Please describe.**
Currently, when using the S3 CSI driver, there is no option to specify a bucket name directly within the `StorageClass` configuration. This can make it challenging to manage multiple PV's needs, as it requires additional inputs and steps or external automation to handle bucket association to a PV. For applications or services that rely on dynamic PV provisioning, this limitation introduces complexity and overhead.

**Describe the solution you'd like in detail**
I would like the ability to specify the bucket name directly in the `StorageClass` configuration. This would allow users to seamlessly get the right bucket. The configuration could look like:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-bucket-storage
provisioner: s3.csi.aws.com
parameters:
  bucketName: my-custom-bucket
```

The S3 CSI driver would limit all of the PV's created by this StorageClass to be on specific bucket.

**Describe alternatives you've considered**
- Using separate automation tools (e.g., Pulumi, custom scripts) to handle bucket usages.

**Additional context**
This feature would enhance the usability of the S3 CSI driver for Kubernetes users, particularly in environments that require dynamic storage provisioning for multiple services or tenants. Having this feature built into the `StorageClass` simplifies both the developer and operations workflows, making it easier to scale and manage storage needs.
