### ISSUE TITLE
Unable to create sonatype nexus pod when using s3 bucket as pvc

### ISSUE THREAD

**Issue by anchaubey** [awslabs/mountpoint-s3-csi-driver#273]
/kind bug
> **_NOTE:_**  If this is a filesystem related bug, please take a look at the [Mountpoint repo](https://github.com/awslabs/mountpoint-s3) to submit a [bug report](https://github.com/awslabs/mountpoint-s3/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml)

**What happened?**

I have created a nexus deployment where I am using s3 static provisioning feature https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/non_root.yaml

My pvc/pv config

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: s3-csi
provisioner: s3.csi.aws.com
parameters:
  mounter: rclone
  region: eu-west-1
  bucket: test-s3-blob-store
  storageClass: STANDARD
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-s3
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: s3.csi.aws.com
    volumeHandle: bucketname/nexus-data
    volumeAttributes:
      bucketName: bucketname
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-csi
  claimRef:
    namespace: namespace
    name: pvc-s3
  mountOptions:
    - allow-delete
    - region eu-west-1
    - allow-other
    - file-mode 0777
    - dir-mode 0777
    - allow-overwrite
    - uid=200
    - gid=200
    - prefix nexus-data/
  volumeMode: Filesystem
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-s3
  namespace: namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: s3-csi
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-s3
---
```

**What you expected to happen?**

I am getting error once the pod is trying to launch as below:-

/sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)
java.lang.RuntimeException: /nexus-data/log/karaf.log (Invalid argument)

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

**Environment** - EKS - 1.30
- Kubernetes version (use `kubectl version`): 
- Driver version: latest
