### ISSUE TITLE
Failed to create S3 client when enabling authenticationSource: pod

### ISSUE THREAD

**Issue by inesshz** [awslabs/mountpoint-s3-csi-driver#293]
/kind bug
> **_NOTE:_**  If this is a filesystem related bug, please take a look at the [Mountpoint repo](https://github.com/awslabs/mountpoint-s3) to submit a [bug report](https://github.com/awslabs/mountpoint-s3/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml)

**What happened?**
I upgraded to version 1.9.0 and set podInfoOnMountCompat to true and also added authenticationSource=pod to PV and I'm now receiving the following :

  Warning  FailedMount       37s (x12 over 9m13s)  kubelet            MountVolume.SetUp failed for volume "s3-pv" : rpc error: code = Internal desc = Could not mount "<bucket-name>" at "/var/lib/kubelet/pods/78dfad8e-3eaf-44ba-93c8-fbf8cae8abc0/volumes/kubernetes.io~csi/s3-pv/mount": Mount failed: Failed to start service output: Error: Failed to create S3 client  Caused by:     0: initial ListObjectsV2 failed for bucket <bucket-name> in region us-east-1     1: Client error     2: No signing credentials available, see CRT debug logs Error: Failed to create mount process

If I switch back to using s3 csi driver role instead of using pod role, it works fine and the mount operation works successfully. 

**What you expected to happen?**
S3 bucket is mounted

**How to reproduce it (as minimally and precisely as possible)?**
I followed the following https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/pod_level_identity.yaml

Deploy s3 csi with podInfoOnMountCompat set to true.

Both driver and pod roles are configured correctly and they have the correct Trusted entities and policies attached (s3:* and kms:*)

Here is the **pv yaml :**
```

spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: s3-pvc
  csi:
    driver: s3.csi.aws.com
    volumeAttributes:
      authenticationSource: pod
      bucketName: <bucket-name>
      stsRegion: us-east-1
    volumeHandle: s3-csi-driver-volume
  mountOptions:
  - allow-delete
  - region us-east-1
  - allow-other
  - allow-overwrite
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem

```

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): 1.30
- Driver version: 1.9.0
