### ISSUE TITLE
How to specify "--cache-xz" option in yaml when create PV

### ISSUE THREAD

**Issue by yangchi** [awslabs/mountpoint-s3-csi-driver#330]
In the v1.11.0 release note, it's mentioned that mountpoint v1.13.0 is now supported and with this version "--cache-xz" option is available. But it's not clear to me how to set this in yaml file when I create the PersistentVolume. Can you please provide an example of such config in the examples folder? Thank you very much!

**Comment by muddyfish** [comment]
Hi, you can specify this with the CSI Driver using the argument list `mountOptions`.

Here's an example that uses the `cache-xz` argument:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region us-west-2
    - prefix some-s3-prefix/
    - cache-xz amzn-s3-demo-bucket--usw2-az1--x-s3
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: s3-csi-driver
```

I'll leave this open until we push an update with an example to the codebase however
