### ISSUE TITLE
Feature - allow setting the S3 storage class for new uploads

### ISSUE THREAD

**Issue by dms486** [awslabs/mountpoint-s3-csi-driver#333]
/feature

**Is your feature request related to a problem? Please describe.**
When creating a Persistent Volume, it would be helpful to have a an option to specify the storage class for objects created/updated in the S3 bucket

**Describe the solution you'd like in detail**
Possibly an additional mountOption to specify the storage class (ex. STANDARD or INTELLIGENT_TIERING)

**Describe alternatives you've considered**
Using a lifecycle policy to transition objects between storage classes. But if I'd like objects in INTELLIGENT_TIERING as soon as possible, I'd still incur a transition cost to move the objects

**Comment by dannycjones** [comment]
Hey @dms486, Mountpoint and the CSI driver already supports this by using Mountpoint's `--storage-class <STORAGE-CLASS>` option: https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#s3-storage-classes

To use this in CSI driver, you can use this argument in the list of `mountOption`.

It would look something like this:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: default # Namespace is required even though it's in "default" namespace.
    name: s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region us-west-2
    - prefix some-s3-prefix/
    - storage-class STANDARD
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: s3-csi-driver
```

I'll close this issue for now, let us know if you have any issues with it.
