### ISSUE TITLE
Feature - Support for Pod-Level Identity Using AWS Credentials

### ISSUE THREAD

**Issue by aminmr** [awslabs/mountpoint-s3-csi-driver#334]
/feature

**Is your feature request related to a problem? Please describe.**
The Mountpoint for Amazon S3 CSI Driver currently supports pod-level credentials only through IRSA. This creates limitations for users of  S3-compatible storage solutions, such as Ceph. These users cannot utilize pod-level credentials effectively and are restricted to driver-level credential configurations.

**Describe the solution you'd like in detail**
I would like the ability to define pod-level credentials using the following AWS environment variables:

```AWS_ACCESS_KEY_ID```
```AWS_SECRET_ACCESS_KEY```
```AWS_SESSION_TOKEN```

For security purposes, these variables could be passed to the pods via Kubernetes secrets. This feature would improve flexibility for S3-compatible storage while allowing credentials to be managed at the pod level.

**Describe alternatives you've considered**
The only current alternative is to configure credentials at the driver level. However, this approach lacks the granularity needed for pod-level configurations and does not meet the requirements for non-EKS Kubernetes environments or S3-compatible backends.

I am also willing to contribute to the development of this feature if guidance and support from the maintainers are available.

**Comment by vladem** [comment]
Hi @aminmr, thanks for the feature request! We'll be happy to gather more feedback on it before starting the implementation. Generally, the use of static credentials is [not recommended](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#bp-workloads-use-roles), but we do recognize that there are [use cases](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#update-access-keys) where their usage is required.

With IRSA, service accounts are [annotated](https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/pod_level_identity.yaml#L80) with the role they need to assume. If we decide to proceed with the implementation, we'll need to define a way of associating static credentials with the service account.

**Comment by aminmr** [comment]
Hi @vladem,

Thanks for the response! I understand the concerns about static credentials. If you decide to move forward, I'm happy to help define how to associate them with the service account through annotations.

Thanks!

**Comment by pawanpnvda** [comment]
We have successfully used the pod-level IRSA to mount S3 buckets on EKS clusters. But as mentioned before, some S3-compatible storage solutions, such as Ceph, or OCI buckets can not use this approach.

Instead of configuring a single CSI driver level AWS credentials, an alternative could be configuring the AWS credential per Persistent Volume. I am proposing the use of "nodePublishSecretRef" field in the Persistent Volume object to specify the K8S secret which stores the required access key and secret key. We can introduce a new authenticationSource (other than driver and pod) as "persistentVolume".

Workflow
1. User creates a Kubernetes Secret containing S3 credentials
2. User creates a PV specification referencing the Secret via `nodePublishSecretRef`
3. CSI Driver reads the Secret during volume mount operations (by parsing the "Secrets" map in NodePublishVolumeRequest)
4. CSI Driver uses the credentials from the Secret to authenticate with S3 compatible storage system.

```
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  Namespace: default
type: Opaque
data:
  key_id: <AWS_ACCESS_KEY_ID> # Needed for S3 compatible storage bucket access
  access_key: <AWS_SECRET_ACCESS_KEY> # Needed for S3 compatible storage bucket access
```

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-compatible-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: s3.csi.aws.com
    volumeHandle: <unique-volume-id>
    volumeAttributes:
      bucketName: <S3_COMPATIBLE_BUCKET_NAME>
      authenticationSource: persistentVolume # A new authentication source
    nodePublishSecretRef:
      name: s3-credentials # The name of the K8S secret created above
      namespace: default # The namespace in which K8S secret was created
```

CSI Driver Changes

1. Modify the NodePublishVolume function to parse the Secrets field in [NodePublishVolumeRequest](https://pkg.go.dev/github.com/container-storage-interface/spec@v1.9.0/lib/go/csi#NodePublishVolumeRequest). This field will be populated with the K8S secret configured in nodePublishSecretRef. 
2. Extract the access key and secret key from the Secret.
3. Use these credentials for S3 authentication instead of driver-level secrets.
4. Note that the K8S service account associated with the CSI driver needs to have the ClusterRole with permissions to read Secrets from a given namespace.
