### ISSUE TITLE
mount failed, client error wrong region

### ISSUE THREAD

**Issue by elebertus** [awslabs/mountpoint-s3-csi-driver#375]
/kind bug
> **_NOTE:_**  If this is a filesystem related bug, please take a look at the [Mountpoint repo](https://github.com/awslabs/mountpoint-s3) to submit a [bug report](https://github.com/awslabs/mountpoint-s3/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml)

**What happened?**

When creating a pv/pvc/deployment with these values:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
  namespace: "rce"
spec:
  capacity:
    storage: 1200Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: "rce" # Namespace is required even though it's in "default" namespace.
    name: s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region us-west-2
    - prefix filebrowser/
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: s3-csi-driver
      stsRegion: us-west-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: "rce"
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: s3-pv # Name of your PV
```
This error is encountered
```
MountVolume.SetUp failed for volume "s3-pv" : rpc error: code = Internal desc = Could not mount "s3-csi-driver" at "/var/lib/kubelet/pods/46d79d61-98f8-4def-9324-3106c528af36/volumes/kubernetes.io~csi/s3-pv/mount": Mount failed: Failed to start service output: Error: Failed to create S3 client  Caused by:                                                                          0: initial ListObjectsV2 failed for bucket s3-csi-driver in region us-west-2
1: Client error
2: Wrong region (expecting eu-west-1) Error: Failed to create mount process
```

No s3 endpoints exist in the connected vpc,  all of the infra is in us-west-2. For our test infra in general we don't even us the  eu-west-1 region. I'm not sure where this reference is even coming from.

**What you expected to happen?**

Client is instantiated with the correct region.

**How to reproduce it (as minimally and precisely as possible)?**

Not really sure as this is a very plain deployment following the documentation.

**Anything else we need to know?**:

Additionally from the mountpoint-s3 docs there is reference to setting `AWS_EC2_METADATA_DISABLED=true`, `AWS_REGION=us-west-2`,`AWS_DEFAULT_REGION=us-west-2` in the s3-csi-node's daemonset containers (all) environment blocks with no result.

**Environment**

EKS version 1.29
addon version v1.11.0-eksbuild.1
