### ISSUE TITLE
Issue when mounting subPath with prefix

### ISSUE THREAD

**Issue by kingFP** [awslabs/mountpoint-s3-csi-driver#411]
/kind bug

**What happened?**
I am mounting an s3 bucket to mount specific files of the bucket into my pod, Mounting a complete directory works fine. However when I add a subPath to the container definition, it errors out.
I get the following error
`Error: failed to prepare subPath for volumeMount "persistent-storage" of container "app"`
The errors on kubelet are as following
```
kubelet[2791]: E0311 20:55:26.796748    2791 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"app\" with CreateContainerConfigError: \"failed to prepare subPath for volumeMount \\\"persistent-storage\\\" of container \\\"app\\\"\"" pod="phnamespace/s3-app-pathbased" podUID="e5ce5830-9e10-4fbc-ade2-4c872cb11ee6"
kubelet[2791]: E0311 20:55:40.732424    2791 kubelet_pods.go:210] "Could not determine if subPath exists, will not attempt to change its permissions" path="/var/lib/kubelet/pods/e5ce5830-9e10-4fbc-ade2-4c872cb11ee6/volumes/kubernetes.io~csi/mys3-pv/mount/check.txt"
kubelet[2791]: E0311 20:55:40.759754    2791 kubelet_pods.go:237] "Failed to prepare subPath for volumeMount of the container" err="error resolving symlinks in \"/var/lib/kubelet/pods/e5ce5830-9e10-4fbc-ade2-4c872cb11ee6/volumes/kubernetes.io~csi/mys3-pv/mount/check.txt\": lstat /var/lib/kubelet/pods/e5ce5830-9e10-4fbc-ade2-4c872cb11ee6/volumes/kubernetes.io~csi/mys3-pv/mount/check.txt: input/output error" containerName="app" volumeMountName="persistent-storage"
```

**What you expected to happen?**
I should be able to mount specific files from s3 into my pod

**How to reproduce it (as minimally and precisely as possible)?**
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mys3-pv
spec:
  capacity:
    storage: 1200Gi # ignored, required
  accessModes:
    - ReadOnlyMany # supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: phnamespace # Namespace is required even though it's in "default" namespace.
    name: mys3-pvc # Name of your PVC
  mountOptions:
    - prefix myprefix/
    - region us-west-2
    - file-mode 0777
    - dir-mode 0777
  csi:
    driver: s3.csi.aws.com # required
    volumeHandle: mys3-pv # must be unique
    volumeAttributes:
      bucketName: mys3-bucket
      region: us-west-2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mys3-pvc
spec:
  accessModes:
    - ReadOnlyMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi # Ignored, required
  volumeName: mys3-pv # Name of your PV
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-app-working
spec:
  serviceAccountName: pi-placeholder
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from the container' ; ls /mnt ; tail -F /dev/null"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /mnt/
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: mys3-pvc
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-app-pathbased
spec:
  serviceAccountName: pi-placeholder
  containers:
    - name: app
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo 'Hello from the container' ; ls /bin ; tail -F /dev/null"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /bin
          subPath: check.txt
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: mys3-pvc
```

**Anything else we need to know?**:
The bucket is on the following structure
- bucket/myprefix/check1.txt
- bucket/myprefix/check2.txt

The `s3-app-pathbased` from the above yaml is just a representation of what I want to do.
My pod already has some data in the image that I want to append into an existing directory, so that the folder will look like this.
/datafolder/embedded-file-from-docker-image1
/datafolder/embedded-file-from-docker-image2
/datafolder/embedded-file-from-docker-image3
/datafolder/check1.txt
/datafolder/check2.txt

**Environment**
- Kubernetes version (use `kubectl version`):
Server Version: v1.29.13-eks-8cce635
- Driver version:
v1.11.0-eksbuild.1
