### ISSUE TITLE
Problem with allow-delete option causing file access issues in S3 CSI Driver

### ISSUE THREAD

**Issue by chiju** [awslabs/mountpoint-s3-csi-driver#463]
When the allow-delete option is enabled in the mountOptions of the PersistentVolume configuration, I encounter issues with accessing and serving files. Specifically, my Nginx container is unable to serve files correctly, and I see 404 Not Found errors in the Nginx logs. When I comment out the allow-delete option, the issue resolves, and Nginx is able to serve the files as expected.

Environment:
Kubernetes version: v1.32 

S3 Bucket: example-bucket (located in eu-central-1)

StorageClass name: s3-sc

Mount Options:

```yaml
mountOptions:
  - uid=33
  - gid=33
  - allow-other
  #- allow-delete
```

Logs:
In my Nginx container logs, I see the following error when the allow-delete option is enabled:

```
2025/05/12 08:20:44 [error] 28#28: *1170 open() "/path/76/preview/page-0.jpg" failed (2: No such file or directory), client: 192.168.39.229, server: x.com, request: "GET /api/documents/76/preview/0 HTTP/1.1", upstream: "fastcgi://10.100.32.19:9000", host: "x.com", referrer: "https://x.com/3/folder/256/document/76"
```

Configuration:
Here’s the relevant portion of the PersistentVolume configuration:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-sc
  mountOptions:
    - uid=33
    - gid=33
    - allow-other
    #- allow-delete
  csi:
    driver: s3.csi.aws.com
    volumeHandle: s3-csi-vol
    volumeAttributes:
      bucketName: example-bucket
      region: eu-central-1
```

Expected Behavior:

I expect that enabling the allow-delete option would not interfere with file access and allow my application to read and serve files correctly from the mounted S3 bucket.

Steps to Reproduce:

Configure a Kubernetes PersistentVolume with the allow-delete option under mountOptions.

Deploy a pod with an Nginx container that tries to serve files from the mounted S3 bucket.

Access a file that should be served by Nginx, e.g., GET /assets/3/76/preview/page-0.jpg.

Observe the 404 Not Found errors in the Nginx logs.

Comment out the allow-delete option and re-deploy.

The issue is resolved, and files are served correctly.

Additional Information:
I have confirmed that the file paths are correct in the S3 bucket.

The issue only occurs when allow-delete is enabled.

I have tested using both the fuse mounter and other configurations.

Please let me know if further details are needed to assist in diagnosing this issue.

Thanks for your help!
